//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        public int DoktorNo { get; set; }
        public string AdSoyad { get; set; }
        public string Brans { get; set; }
        public string Uzmanlık { get; set; }
        public Nullable<int> RaporNo { get; set; }
    }
}
