//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaBilgileri
    {
        public int BilgiNo { get; set; }
        public string Teshis { get; set; }
        public Nullable<int> MUcret { get; set; }
        public string Recete { get; set; }
        public string TakipDurum { get; set; }
        public Nullable<int> HastaNo { get; set; }
    }
}
