//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HastaneEntities4 : DbContext
    {
        public HastaneEntities4()
            : base("name=HastaneEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktorlar> Doktorlars { get; set; }
        public virtual DbSet<HastaBilgileri> HastaBilgileris { get; set; }
        public virtual DbSet<Hastalar> Hastalars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Raporlar> Raporlars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int DoktorEkle(string adSoyad, string brans, string uzmanlık, Nullable<int> raporNo)
        {
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var bransParameter = brans != null ?
                new ObjectParameter("Brans", brans) :
                new ObjectParameter("Brans", typeof(string));
    
            var uzmanlıkParameter = uzmanlık != null ?
                new ObjectParameter("Uzmanlık", uzmanlık) :
                new ObjectParameter("Uzmanlık", typeof(string));
    
            var raporNoParameter = raporNo.HasValue ?
                new ObjectParameter("RaporNo", raporNo) :
                new ObjectParameter("RaporNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoktorEkle", adSoyadParameter, bransParameter, uzmanlıkParameter, raporNoParameter);
        }
    
        public virtual ObjectResult<DoktorListele_Result> DoktorListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoktorListele_Result>("DoktorListele");
        }
    
        public virtual int DoktorSil(Nullable<int> doktorNo)
        {
            var doktorNoParameter = doktorNo.HasValue ?
                new ObjectParameter("DoktorNo", doktorNo) :
                new ObjectParameter("DoktorNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoktorSil", doktorNoParameter);
        }
    
        public virtual int DoktorYenile(Nullable<int> doktorNo, string adSoyad, string brans, string uzmanlık, Nullable<int> raporNo)
        {
            var doktorNoParameter = doktorNo.HasValue ?
                new ObjectParameter("DoktorNo", doktorNo) :
                new ObjectParameter("DoktorNo", typeof(int));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var bransParameter = brans != null ?
                new ObjectParameter("Brans", brans) :
                new ObjectParameter("Brans", typeof(string));
    
            var uzmanlıkParameter = uzmanlık != null ?
                new ObjectParameter("Uzmanlık", uzmanlık) :
                new ObjectParameter("Uzmanlık", typeof(string));
    
            var raporNoParameter = raporNo.HasValue ?
                new ObjectParameter("RaporNo", raporNo) :
                new ObjectParameter("RaporNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoktorYenile", doktorNoParameter, adSoyadParameter, bransParameter, uzmanlıkParameter, raporNoParameter);
        }
    
        public virtual int HastaBilgileriEkle(string teshis, Nullable<decimal> mUcret, string recete, string takipDurum, Nullable<int> hastaNo)
        {
            var teshisParameter = teshis != null ?
                new ObjectParameter("Teshis", teshis) :
                new ObjectParameter("Teshis", typeof(string));
    
            var mUcretParameter = mUcret.HasValue ?
                new ObjectParameter("MUcret", mUcret) :
                new ObjectParameter("MUcret", typeof(decimal));
    
            var receteParameter = recete != null ?
                new ObjectParameter("Recete", recete) :
                new ObjectParameter("Recete", typeof(string));
    
            var takipDurumParameter = takipDurum != null ?
                new ObjectParameter("TakipDurum", takipDurum) :
                new ObjectParameter("TakipDurum", typeof(string));
    
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaBilgileriEkle", teshisParameter, mUcretParameter, receteParameter, takipDurumParameter, hastaNoParameter);
        }
    
        public virtual int HastaBilgileriSil(Nullable<int> bilgiNo)
        {
            var bilgiNoParameter = bilgiNo.HasValue ?
                new ObjectParameter("BilgiNo", bilgiNo) :
                new ObjectParameter("BilgiNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaBilgileriSil", bilgiNoParameter);
        }
    
        public virtual int HastaBilgileriYenile(Nullable<int> bilgiNo, string teshis, Nullable<decimal> mUcret, string recete, string takipDurum, Nullable<int> hastaNo)
        {
            var bilgiNoParameter = bilgiNo.HasValue ?
                new ObjectParameter("BilgiNo", bilgiNo) :
                new ObjectParameter("BilgiNo", typeof(int));
    
            var teshisParameter = teshis != null ?
                new ObjectParameter("Teshis", teshis) :
                new ObjectParameter("Teshis", typeof(string));
    
            var mUcretParameter = mUcret.HasValue ?
                new ObjectParameter("MUcret", mUcret) :
                new ObjectParameter("MUcret", typeof(decimal));
    
            var receteParameter = recete != null ?
                new ObjectParameter("Recete", recete) :
                new ObjectParameter("Recete", typeof(string));
    
            var takipDurumParameter = takipDurum != null ?
                new ObjectParameter("TakipDurum", takipDurum) :
                new ObjectParameter("TakipDurum", typeof(string));
    
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaBilgileriYenile", bilgiNoParameter, teshisParameter, mUcretParameter, receteParameter, takipDurumParameter, hastaNoParameter);
        }
    
        public virtual ObjectResult<HastaBilgisiListele_Result> HastaBilgisiListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaBilgisiListele_Result>("HastaBilgisiListele");
        }
    
        public virtual int HastaEkle(string adSoyad, Nullable<int> yas, string adres)
        {
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var yasParameter = yas.HasValue ?
                new ObjectParameter("Yas", yas) :
                new ObjectParameter("Yas", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaEkle", adSoyadParameter, yasParameter, adresParameter);
        }
    
        public virtual ObjectResult<HastaListele_Result> HastaListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HastaListele_Result>("HastaListele");
        }
    
        public virtual int HastaSil(Nullable<int> hastaNo)
        {
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaSil", hastaNoParameter);
        }
    
        public virtual int HastaYenile(Nullable<int> hastaNo, string adSoyad, Nullable<int> yas, string adres)
        {
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var yasParameter = yas.HasValue ?
                new ObjectParameter("Yas", yas) :
                new ObjectParameter("Yas", typeof(int));
    
            var adresParameter = adres != null ?
                new ObjectParameter("Adres", adres) :
                new ObjectParameter("Adres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HastaYenile", hastaNoParameter, adSoyadParameter, yasParameter, adresParameter);
        }
    
        public virtual ObjectResult<KullaniciGiris_Result> KullaniciGiris(string kullaniciAdi, string sifre)
        {
            var kullaniciAdiParameter = kullaniciAdi != null ?
                new ObjectParameter("KullaniciAdi", kullaniciAdi) :
                new ObjectParameter("KullaniciAdi", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("Sifre", sifre) :
                new ObjectParameter("Sifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KullaniciGiris_Result>("KullaniciGiris", kullaniciAdiParameter, sifreParameter);
        }
    
        public virtual int RaporEkle(string raporTanimi, string olusturmaTarihi, string sonTarihi, Nullable<int> hastaNo)
        {
            var raporTanimiParameter = raporTanimi != null ?
                new ObjectParameter("RaporTanimi", raporTanimi) :
                new ObjectParameter("RaporTanimi", typeof(string));
    
            var olusturmaTarihiParameter = olusturmaTarihi != null ?
                new ObjectParameter("OlusturmaTarihi", olusturmaTarihi) :
                new ObjectParameter("OlusturmaTarihi", typeof(string));
    
            var sonTarihiParameter = sonTarihi != null ?
                new ObjectParameter("SonTarihi", sonTarihi) :
                new ObjectParameter("SonTarihi", typeof(string));
    
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RaporEkle", raporTanimiParameter, olusturmaTarihiParameter, sonTarihiParameter, hastaNoParameter);
        }
    
        public virtual ObjectResult<RaporListele_Result> RaporListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RaporListele_Result>("RaporListele");
        }
    
        public virtual int RaporSil(Nullable<int> raporNo)
        {
            var raporNoParameter = raporNo.HasValue ?
                new ObjectParameter("RaporNo", raporNo) :
                new ObjectParameter("RaporNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RaporSil", raporNoParameter);
        }
    
        public virtual int RaporYenile(Nullable<int> raporNo, string raporTanimi, string olusturmaTarihi, string sonTarihi, Nullable<int> hastaNo)
        {
            var raporNoParameter = raporNo.HasValue ?
                new ObjectParameter("RaporNo", raporNo) :
                new ObjectParameter("RaporNo", typeof(int));
    
            var raporTanimiParameter = raporTanimi != null ?
                new ObjectParameter("RaporTanimi", raporTanimi) :
                new ObjectParameter("RaporTanimi", typeof(string));
    
            var olusturmaTarihiParameter = olusturmaTarihi != null ?
                new ObjectParameter("OlusturmaTarihi", olusturmaTarihi) :
                new ObjectParameter("OlusturmaTarihi", typeof(string));
    
            var sonTarihiParameter = sonTarihi != null ?
                new ObjectParameter("SonTarihi", sonTarihi) :
                new ObjectParameter("SonTarihi", typeof(string));
    
            var hastaNoParameter = hastaNo.HasValue ?
                new ObjectParameter("HastaNo", hastaNo) :
                new ObjectParameter("HastaNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RaporYenile", raporNoParameter, raporTanimiParameter, olusturmaTarihiParameter, sonTarihiParameter, hastaNoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
