//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int RaporNo { get; set; }
        public string RaporTanimi { get; set; }
        public string OlusturmaTarihi { get; set; }
        public string SonTarihi { get; set; }
        public Nullable<int> HastaNo { get; set; }
    }
}
